#!/bin/sh

USER="Owl-Boy"
TOKEN="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"

notifications=$(echo "user = \"$USER:$TOKEN\"" | curl -sf -K- https://api.github.com/notifications | jq ".[].unread" | grep -c true)

if [ "$notifications" -gt 0 ]; then
    echo "$notifications"
else
    echo "0"
fi
